# Generated by Django 4.0.6 on 2022-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='room',
            name='screen_avail',
            field=models.BooleanField(default=False),
        ),
    ]
