# Generated by Django 4.0.6 on 2022-07-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0003_alter_user_username_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='room_id',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room_id', 'date')},
        ),
    ]
