# Generated by Django 4.0.6 on 2022-07-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0004_rename_room_reservation_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
