# Generated by Django 4.0.6 on 2022-07-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0005_alter_room_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
