# Generated by Django 4.0.6 on 2022-07-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0006_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room_id', 'date')},
        ),
    ]
